---
# defaults file for cicd
workspace: "/tmp/workspace"
maven_version: 3.6.3
backend_tag: "3.0.0"
frontend_tag: v3.0.0
release_tag: master
stack_name: bento
tag: latest
backend_url: http://localhost
image_tag: latest
connector_name: local
update: no
schema_file: bento-extended.graphql
