---
- name: Check if workspace exists
  stat:
    path: "{{workspace}}"
  register: bento_result

- name: remove old bento
  file:
    path: "{{workspace}}"
    state: absent
  when: bento_result.stat.exists

- name: clone dataloader
  git:
    repo: "{{data_repo}}"
    dest: "{{workspace}}/data"
    track_submodules: yes
    update: yes
    version: master

- name: clone bento-custodian
  git:
    repo: 'https://github.com/CBIIT/bento-custodian'
    dest: "{{workspace}}/bento-custodian"

- name: update settings
  template:
    dest: "{{workspace}}/data/data-loader/config.yml"
    src: config.yml.j2

- name: install python3
  yum:
    name: python3
    state: installed

- name: pip install requirements
  pip:
    requirements: "{{workspace}}/data/data-loader/requirements.txt"
    executable: pip3

- name: set neo4j password
  uri:
    url: http://{{neo4j_ip}}:7474/user/neo4j/password
    user: neo4j
    password: neo4j
    method: POST
    body: >
      {"password":"{{neo4j_password}}"}
    body_format: json
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
  when: init_db == "yes"

- name: loader data
  shell:
    cmd: >
      python3
      loader.py 
      {{workspace}}/data/dataloader/config.yml
    chdir: "{{workspace}}/data"
  register: data_loader

- name: show dataloader output
  debug:
    msg: "{{data_loader}}"
