---
- name: install python expect module
  pip:
    name:
      - pexpect
      - docker-py

- name: login to docker
  expect:
    command: gcloud auth configure-docker {{gcp_region}}-docker.pkg.dev
    responses:
      Do you want to continue (Y/n)?: Y

- name: push cbiitssrepo/custodian-backend to gcp registry
  docker_image:
    name: "cbiitssrepo/custodian-backend:latest"
    repository: "{{gcp_region}}-docker.pkg.dev/{{gcp_project}}/{{env}}/backend"
    tag: latest
    source: pull

- name: push {{gcp_region}}-docker.pkg.dev/{{gcp_project}}/{{env}}/backend to registry
  command: docker push {{gcp_region}}-docker.pkg.dev/{{gcp_project}}/{{env}}/backend:latest

- name: push cbiitssrepo/custodian-frontend to gcp registry
  docker_image:
    name: "cbiitssrepo/custodian-frontend:latest"
    repository: "{{gcp_region}}-docker.pkg.dev/{{gcp_project}}/{{env}}/frontend"
    tag: latest
    source: pull

- name: push {{gcp_region}}-docker.pkg.dev/{{gcp_project}}/{{env}}/frontend to registry
  command: docker push {{gcp_region}}-docker.pkg.dev/{{gcp_project}}/{{env}}/frontend:latest