---
# tasks file for docker
- name: install epel-release
  yum: 
    name:
      - epel-release
- name: install systems packages needed for docker
  yum:
    name: 
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python-setuptools
      - firewalld
      - python-pip
      - docker-compose
    state: installed

- name: install docker python module
  pip:
    name: docker
    
- name: add docker repo 
  command: >
    yum-config-manager --add-repo 
    https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: installed
    
- name: enable and start docker
  service:
    name: docker
    enabled: yes
    state: restarted


 



