---
- name: setup deploy custodian
  hosts: all
  connection: local
  become: yes
  gather_facts: yes

  tasks:
    - name: build custodian
      include_role:
        name: cloud-run
        tasks_from: build
    

