---
- name: load data to neo4j db
  hosts: bastion
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yaml

  tasks:
    - name: perform data loading
      include_role:
        name: data-loader
        